siteapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

import siteapp.views as views
import siteapp.views_landing as views_landing
from .good_settings_helpers import signup_wrapper

urlpatterns = [
    url(r"^$", views.homepage, name="homepage"),
    url(r"^(privacy|terms-of-service|love-assessments)$", views.shared_static_pages),

    url(r'^api/v1/projects/(?P<project_id>\d+)/answers$', views_landing.project_api),
    url(r'^media/users/(\d+)/photo/(\w+)', views_landing.user_profile_photo),

    # incoming email hook for responses to notifications
    url(r'^notification_reply_email_hook$', views_landing.notification_reply_email_hook),

    # Django admin site
    url(r'^admin/', admin.site.urls),

    # apps
    url(r"^tasks/", include("guidedmodules.urls")),
    url(r"^discussion/", include("discussion.urls")),

    # app store
    url(r'^store$', views.apps_catalog),
    url(r'^store/(?P<source_slug>.*)/(?P<app_name>.*)$', views.apps_catalog_item),

    # projects
    url(r"^projects$", views.project_list),
    url(r'^projects/(\d+)/__rename$', views.rename_project, name="rename_project"),
    url(r'^projects/(\d+)/__delete$', views.delete_project, name="delete_project"),
    url(r'^projects/(\d+)/__admins$', views.make_revoke_project_admin, name="make_revoke_project_admin"),
    url(r'^projects/(\d+)/__export$', views.export_project, name="export_project"),
    url(r'^projects/(\d+)/__import$', views.import_project_data, name="import_project_data"),
    url(r'^projects/(\d+)/(?:[\w\-]+)()$', views.project), # must be last because regex matches some previous URLs
    url(r'^projects/(\d+)/(?:[\w\-]+)(/startapps)$', views.project_start_apps), # must be last because regex matches some previous URLs
    url(r'^projects/(\d+)/(?:[\w\-]+)(/list)$', views.project_list_all_answers), # must be last because regex matches some previous URLs
    url(r'^projects/(\d+)/(?:[\w\-]+)(/outputs)$', views.project_outputs), # must be last because regex matches some previous URLs
    url(r'^projects/(\d+)/(?:[\w\-]+)(/api)$', views.project_api), # must be last because regex matches some previous URLs
    url(r'^projects/(\d+)/(?:[\w\-]+)(/upgrade)$', views.project_upgrade_app), # must be last because regex matches some previous URLs

    # org groups
    url(r'^groups$', views_landing.org_groups),
    url(r'^groups/new$', views_landing.new_org_group),
    url(r"^(?P<org_slug>.*)/projects$", views_landing.org_group_projects),

    # api
    url(r'^api-keys$', views.show_api_keys, name="show_api_keys"),

    # invitations
    url(r'^invitation/_send$', views.send_invitation, name="send_invitation"),
    url(r'^invitation/_cancel$', views.cancel_invitation, name="cancel_invitation"),
    url(r'^invitation/accept/(?P<code>.+)$', views.accept_invitation, name="accept_invitation"),

    # administration
    url(r'^settings$', views.organization_settings),
    url(r'^settings/_save$', views.organization_settings_save),
]

if 'django.contrib.auth.backends.ModelBackend' in settings.AUTHENTICATION_BACKENDS:
    # If username/password logins are enabled, add the login pages.
    urlpatterns += [
        # auth
        # next line overrides signup with our own view so we can monitor signup attempts, can comment out to go back to allauth's functionality
        url(r'^accounts/signup/', signup_wrapper, name="account_signup"),
        url(r'^accounts/', include('allauth.urls')),
    ]

import notifications.urls
urlpatterns += [
    url('^user/notifications/', include(notifications.urls, namespace='notifications')),
    url('^_mark_notifications_as_read', views.mark_notifications_as_read),
]

if settings.DEBUG: # also in urls_landing
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug_toolbar__/', include(debug_toolbar.urls)),
    ]

guidedmodules/models.py
from django.db import models, transaction
from django.utils import timezone
from django.conf import settings

from jsonfield import JSONField

from collections import OrderedDict
import uuid

from .module_logic import ModuleAnswers, render_content
from .answer_validation import validator
from siteapp.models import User, Organization, Project, ProjectMembership

class AppSource(models.Model):
    is_system_source = models.BooleanField(default=False, help_text="This field is set to True for a single AppSource that holds the system modules such as user profiles.")
    slug = models.CharField(max_length=200, unique=True, help_text="A unique URL-safe string that names this AppSource.")
    spec = JSONField(help_text="A load_modules ModuleRepository spec.", load_kwargs={'object_pairs_hook': OrderedDict})

    trust_assets = models.BooleanField(default=False, help_text="Are assets trusted? Assets include Javascript that will be served on our domain, Python code included with Modules, and Jinja2 templates in Modules.")
    available_to_all = models.BooleanField(default=True, help_text="Turn off to restrict the Modules loaded from this source to particular organizations.")
    available_to_orgs = models.ManyToManyField(Organization, blank=True, help_text="If available_to_all is False, list the Organizations that can start projects defined by Modules provided by this AppSource.")

    created = models.DateTimeField(auto_now_add=True, db_index=True)
    updated = models.DateTimeField(auto_now=True, db_index=True)

    extra = JSONField(blank=True, help_text="Additional information stored with this object.")

    def __str__(self):
        # for the admin
        return self.slug

    def get_description(self):
        # Return a description of the connection that this AppSource
        # provides. The output should be safe to share with users of
        # the site --- so credentials should not be returned in this
        # string.
        if self.spec["type"] == "null":
            return "null source"
        if self.spec["type"] == "local":
            return "local filesystem at %s" % self.spec.get("path")
        if self.spec["type"] == "git":
            try:
                # Remove credentials from URL.
                from urllib.parse import urlsplit, urlunsplit
                (scheme, host, path, query, fragment) = urlsplit(self.spec["url"])
                host = host.split("@", 1)[-1]

                # Set fragment to git branch.
                fragment = self.spec.get("branch")

                # Re-form URL.
                url = urlunsplit((scheme, host, path, query, fragment))
            except Exception:
                url = "<invalid url>"
            return url + ("@"+self.spec["branch"] if self.spec.get("branch") else "")
        if self.spec["type"] == "github":
            return "github.com/%s" % self.spec.get("repo")

    def make_cache_stale_key(self):
        import xxhash, json
        payload = b""
        payload += json.dumps(self.spec).encode("utf8")
        payload += self.updated.isoformat().encode("ascii")
        return xxhash.xxh64(payload).hexdigest()

    def open(self):
        # Return an AppSourceConnection instance for this source.
        from .app_source_connections import AppSourceConnection
        return AppSourceConnection.create(self, self.spec)

    def get_available_apps(self):
        with self.open() as src:
            for app in src.list_apps():
                yield {
                    "name": app.name,
                    "new_version_number": app.get_new_version_number(),
                    "versions_in_catalog": app.get_appversions(),
                    "hidden_versions": app.get_hidden_appversions(),
                }

    def add_app_to_catalog(self, appname):
        from .app_loading import load_app_into_database
        with self.open() as conn:
            app = conn.get_app(appname)
            appver = load_app_into_database(app)
            appver.show_in_catalog = True
            appver.save()
        return appver

class AppVersion(models.Model):
    source = models.ForeignKey(AppSource, related_name="appversions", on_delete=models.CASCADE, help_text="The source repository where this AppVersion came from.")
    appname = models.CharField(max_length=200, db_index=True, help_text="The name of the app in the AppSource.")

        # the field below is a NullBooleanField because the unique constraint doesn't kick in
        # for NULLs but does for False/True, and we want the constraint to apply only for True.
    system_app = models.NullBooleanField(default=None, help_text="Set to True for AppVersions that are the current version of a system app that provides system-expected Modules. A constraint ensures that only one (source, name) pair can be true.")

    catalog_metadata = JSONField(blank=True, help_text="The catalog metadata that was stored in the 'app' module.")
    version_number = models.CharField(blank=True, null=True, max_length=128, help_text="The version number of the compliance app.")
    version_name = models.CharField(blank=True, null=True, max_length=128, help_text="The name of this version/release of the compliance app.")

    asset_files = models.ManyToManyField('guidedmodules.ModuleAsset', help_text="The assets linked to this pack.")
    asset_paths = JSONField(help_text="A dictionary mapping file paths to the content_hashes of assets included in the assets field of this instance.")
    trust_assets = models.BooleanField(default=False, help_text="Are assets trusted? Assets include Javascript that will be served on our domain, Python code included with Modules, and Jinja2 templates in Modules.")

    show_in_catalog = models.BooleanField(default=False, help_text='Whether to show this AppVersion in the compliane app catalog, which allows users to start the app.')

    created = models.DateTimeField(auto_now_add=True, db_index=True)
    updated = models.DateTimeField(auto_now=True, db_index=True)

    class Meta:
        unique_together = [
            ("source", "appname", "system_app")
        ]

    def __str__(self):
        # For the admin.
        return "%s [%d] (from %s)" % (self.appname, self.id, self.source)

    def __repr__(self):
        # For debugging.
        return "<AppVersion [%d] %s from %s>" % (self.id, self.appname, self.source)

    def get_version_display(self):
        v = self.version_number or self.created.isoformat()
        if self.version_name:
            v += " (" + self.version_name + ")"
        return v

    def get_asset(self, asset_path):
        if asset_path not in self.asset_paths:
            raise ValueError("{} is not an asset in {}.".format(asset_path, self))
        return self.asset_files.get(source=self.source, content_hash=self.asset_paths[asset_path]).file

    def catalog_metadata_yaml(self):
        import rtyaml
        return rtyaml.dump(self.catalog_metadata)

    def is_authoring_tool_enabled(self, user):
        return (self.source.spec["type"] == "local" # so we can save to disk
            and user.has_perm('guidedmodules.change_module'))

    def has_upgrade_priv(self, user):
        # Does a user have permission to ugprade the Modules in this AppVersion?
        # Yes if the user is an admin of all the Projects that the Tasks that use
        # the Modules are in. In practice, that's just during app authoring when
        # the author is testing changes.
        #
        # In the database, we allow AppVersions to be shared across many Projects.
        # (The system AppVersion which holds e.g. the user profile module is
        # shared across many user projects, but that AppVersion is blacklisted
        # from upgrades below.) 
        if self.system_app: return False
        projects = Task.objects.filter(module__app=self).values_list("project", flat=True).distinct()
        if len(projects) == 0:
            # This AppVersion doesn't appear to be in use! Well, lock it down.
            return False
        for project in projects:
            if user not in Project.objects.get(id=project).get_admins():
                return False
        return True

    @staticmethod
    def get_startable_apps(organization):
        # Load all of the startable AppVersions. An AppVersion is startable
        # if its show_in_catalog field is True and its AppSource is available
        # to the organization the request is for, which is true if the AppSoure
        # is available to all organizations or the organization has been whitelisted.
        from django.db.models import Q
        return AppVersion.objects\
            .filter(show_in_catalog=True)\
            .filter(source__is_system_source=False)\
            .filter(Q(source__available_to_all=True) | Q(source__available_to_orgs=organization))
    

def extract_catalog_metadata(app_module, migration=None):
    # Note that this function is used in migration 0044 and so
    # must be compatible to run in the migration and must be
    # preserved so long as migration 0044 exists.
    #
    # app_module.spec and app_module.app are updated.

    app_module.app.catalog_metadata = {
    }

    # Take some top-level fields that apply to both the module and the
    # catalog and copy them into the catalog, leaving it also in the
    # Module.
    for field in ("title", "icon"):
        if field in app_module.spec:
            app_module.app.catalog_metadata[field] = app_module.spec[field]

    # Take the 'catalog', overriding any module-level fields.
    if "catalog" in app_module.spec:
        app_module.app.catalog_metadata.update(app_module.spec["catalog"])
        del app_module.spec["catalog"]

    # Also update the version_number and version_name fields.
    # Except in migration 0044 because those fields don't
    # exist yet. That's handled in migration 0045.
    if migration is None:
        app_module.app.version_number = app_module.app.catalog_metadata.get('version')

templates/org_groups/new_org_group.html
{% extends "../base.html" %}
{% load bootstrap3 %}

{% block title %}
Welcome to Compliance Automation
{% endblock %}

{% block body-wide %}

<div class="container">
    <div class="row">

        <div class="col-md-3" style="margin: 40px 0px 30px 0px;">
          <h2>New group</h2>
          <p>Groups allow you to organize and manage related projects. Members of a group can access all of its unrestriced projects.</p>
        </div>

        <div class="col-md-9" style="margin: 40px 0px 30px 0px;">

            <div class="well">
            <form method="post">
                {% csrf_token %}
                <input type=hidden name=action value=neworg>
                {% bootstrap_form neworg_form %}
                <p><button type="submit" class="btn btn-success">Next &raquo;</button></p>
            </form>
            </div>

        </div>
    </div>
</div>


    {{ block.super }} 
{% endblock %}

{% block scripts %}
<script>
$('#id_name').on('keyup', function() {
    var slug = $(this).val();
    slug = slug.toLowerCase().replace(/[^a-z0-9--]+/g, "-").replace(/^-+/, "").replace(/-+$/, "");
    $('#id_slug').val(slug);
})

{% if request.method == "POST" %}
smooth_scroll_to($('input[name=action][value={{request.POST.action|escapejs}}]').parent('form'));
{% endif %}
</script>
{% endblock %}

templates/org_groups/org_group.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}
Welcome to GovReady Q - {{org.name}}
{% endblock %}

{% block head %}
<style>
.project-image {
  width: 20px;
  float: left;
  margin: 4px 0 5px 8px;
}

.project-text {
}

.project-text h4 {
  margin: 0;
  font-weight: bold;
  font-size: inherit;
}

.project-text > * {
  margin: .5em 0 0 0;
  font-size: 13px;
}

</style>
{% endblock %}

<!-- Remove contextbar from top of page -->
{% block contextbar %}{% endblock %}

% block body-wide %
{% block body %}

<div style="margin-top: 30px">

<div class="container">

<div style="float: right; margin: 0 0.5em 0em 5em;">
  <a id="new-project" href="/store" class="btn btn-success">Start a project</a>
  {% if can_invite_to_org %}
  <a href="#" onclick="show_invite_to_org(); return false;" class="btn btn-success"><i class="glyphicon glyphicon-send"></i> Invite colleague </a>
  {% endif %}
</div>

<h2 class="">{{ org.name }}</h2>
<small style="color: #888;">Group ID: {{ org.id }}</small>

{% if projects|length > 0 %}
<p>You have access to {{ projects|length }} project{{ projects|pluralize }}</p>
{% endif %}

<div class="container">
{% for project in projects %}
<div class="row" style="border-top: 1px solid #aaa;padding: 8px 0px 8px 0px;">
  <div class="col-md-6">
    {% if project.root_task.get_app_icon_url %}
      <a href="{{project.get_absolute_url}}" class="project-image">
        <img src="{{project.root_task.get_app_icon_url}}" class="img-responsive">
      </a>
    {% else %}
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    {% endif %}
    &nbsp;&nbsp;&nbsp;
    <a href="{{project.get_absolute_url}}" style="color: black;">{{project.title}}</a>
  </div>

  <div class="col-md-3">&nbsp;</div>

  <div class="col-md-1">
    <small style="color: #888;">(ID: {{project.id}})</small>
  </div>

  <div class="col-md-2">
      <small style="color: #888;">
      <!-- App version: {{project.root_task.module.spec.catalog.version|force_escape}} -->
      Updated {{project.root_task.updated|naturaltime}}
      <!-- Started: {{project.created|naturaltime}} -->
    </small>
  </div>

</div>

{% endfor %}

{% if projects|length < 2 %}
<div class="container">
  <div class="row" style="margin-top: 60px;">
    <div class="col-md-2"></div>
    <div class="col-md-5">
      <h2>A group is a collection of projects.</h2>

      <p>Think of a group like a folder for your projects.</p>

      <p>The owner of the group can manage group members.</p>
    </div>
    <div class="col-md-3">
        <div class="glyphicon glyphicon-folder-open" style="font-size: 8em; color: rgb(160, 210, 160);"></div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>
{% endif %}

    {{ block.super }} 
{% endblock %}

{% block scripts %}
<script>
</script>
{% endblock %}

templates/org_groups/org_groups.html
{% extends "base.html" %}
{% load q %}

{% block title %}
Your Compliance Projects
{% endblock %}

{% block breadcrumbs %}
<li class="active">Your Compliance Projects</li>
{% endblock %}

{% block head %}
<style>
.btn .glyphicon { margin-right: 6px; }
.btn.btn-success .glyphicon { color: #FFF; }

.lifecycle {
  margin-bottom: 30px;
}
.lifecycle h2 {
  margin: 0 0 1em 0;
}
.lifecycle .stage {
  margin: 0 -10px;
  padding: 10px;
  background-color: rgb(247,247,247);
  border-radius: 5px;
  max-width: 530px; /* so individual cards don't stretch across whole page */
  box-shadow: 0 0 0 1px rgba(0, 0, 0, .1), 0 2px 3px rgba(0, 0, 0, .2);
}
  .lifecycle .stage h3 {
    color: black;
    margin: 5px 0 0 0;
    text-align: center;
  }
  .lifecycle .stage .stage-subhead {
    text-align: center;
    margin-bottom: 15px;
  }

  .project {
    background-color: white;
    padding: 10px;
    margin-bottom: 15px;
    border-radius: 3px;
    border-bottom: 1px solid rgb(204, 204, 204);
  }
    .project-image {
      width: 30px;
      float: right;
      margin: 4px 0 5px 8px;
    }
    .project-text {
    }
    .project-text h4 {
      margin: 0;
      font-weight: bold;
      font-size: inherit;
    }
    .project-text > * {
      margin: .5em 0 0 0;
      font-size: 13px;
    }

  h1.mini {
    font-size: 16px;
    font-family: Hind, sands-serif;
    line-height: 22px;
    color: rgba(51, 51, 51);
    padding: 0px 0px 0px 0px;
    margin: 0px 0px 0px 0px;
  }

  .luna-box {
    border: 1px solid rgb(210, 210, 210);
    height: 160px;
    margin-top: 30px;
    font-size: .8em;
    border-radius: 4px;
    padding: 20px 20px 0px 0px;
  }

  .luna-box div.glyphicon {
    font-size:3em;
    color: rgb(160, 210, 160);
    margin:30px 0px 0px 40px;
  }

</style>
{% endblock %}

<!-- Remove contextbar from top of page -->
{% block contextbar %}{% endblock %}

{% block body %}

<div style="margin-top: 30px">

<div class="container">

{% if org_groups|length > 0 %}

<div style="float: right; margin: 0 0.5em 0em 5em;">
  <a id="new-group" href="/groups/new" class="btn btn-success">Create a group</a>
</div>

<h2 class="">Groups</h2>
{% endif %}

{% if org_groups|length > 0 %}
<p>You have access to {{ org_groups|length }} group{{ org_groups|pluralize }}</p>
{% endif %}

  {% include "org_groups/org_groups_table.html" with org_groups=org_groups %}
  <!-- include "org_groups_table.html" with org_groups=org_groups listid="org-groups" listname="Groups" -->


{% endblock %}

{% block scripts %}
<script>
</script>
{% endblock %}

templates/org_groups/org_groups_table.html
<!-- List of org groups -->
{% load humanize %}

<div class="container">

{% for org_group in org_groups %}
<div class="row" style="border-top: 1px solid #aaa;padding: 8px 0px 8px 0px;">

  <div class="col-md-5">
    <div>
      <span class="glyphicon glyphicon-folder-close"></span>&nbsp;&nbsp;&nbsp;
      <a href="/{{org_group.slug}}/projects" style="color: black;">{{org_group.name}}</a>
    </div>
    <!-- <div><small>This is the group description</small></div> -->
  </div>

  <div class="col-md-4">&nbsp;</div>
  <div class="col-md-1"><small style="color: #888;">ID: {{org_group.id}}</small></div>

  <div class="col-md-2" style="text-align: right;"><small style="color: #888;">Created {{org_group.created|naturaltime}}</small></div>
</div>
{% endfor %}

</div>